# Generated by Django 6.0.3 on 2026-06-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('openGradeBook', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittedFileContent', models.TextField(blank=True, max_length=100000, null=True)),
                ('originalFileName', models.CharField(blank=True, max_length=255, null=True)),
                ('submittedText', models.TextField(blank=True, max_length=100000, null=True)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('isGraded', models.BooleanField(default=False)),
                ('grade', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True)),
                ('teacherFeedback', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('isHidden', models.BooleanField(default=True)),
                ('gradeMax', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('assignmentType', models.CharField(choices=[('submittable', 'Submittable'), ('resubmittable', 'Resubmittable'), ('unsubmittable', 'Unsubmittable')], default='submittable', max_length=20)),
                ('assignmentGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='groups.assignmentgroup')),
            ],
        ),
    ]
