# Generated by Django 6.0.3 on 2026-06-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submittedFileContent',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
