# Generated by Django 6.0.3 on 2026-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_submission_submittedfilecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submittedFileContent',
            field=models.TextField(blank=True, max_length=1300000, null=True),
        ),
    ]
