# Generated by Django 6.0.3 on 2026-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_students_alter_group_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='isHidden',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='openGradeBook',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='isGraded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
