# Generated by Django 6.0.3 on 2026-06-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_group_students_alter_group_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='gradeMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
